import type ru from './ru'

// Английские тексты main: ровно те же ключи, что в ru.ts (лишний или пропущенный — ошибка типа).
export default {
  'command.invalidContext': 'Invalid command context.',
  'command.forbidden': 'Access to this command is denied.',
  'command.invalidInput': 'Invalid command field: {field}.',
  'command.projectNotFound': 'Project “{projectId}” was not found.',
  'command.taskNotFound': 'Task “{taskId}” was not found in the selected project.',
  'command.globalTaskNotFound': 'Global task “{globalTaskId}” was not found in the selected project.',
  'command.requestNotFound': 'Request “{requestId}” was not found in the selected project.',
  'command.questionNotFound': 'Question “{questionId}” was not found in the selected project.',
  'command.rejected': 'The command failed: {reason}.',
  'command.conflict': 'Control is already taken or the command state changed.',
  'command.stale': 'The command result is stale: the project changed or was removed.',
  'runtime.startupTitle': 'Could not start Orca',
  'runtime.profileBusy': 'This Orca profile is already open in another process. Close it before starting Desktop.',
  'runtime.profileUnavailable': 'Could not acquire profile ownership: the local endpoint is occupied or unavailable.',
  'runtime.profileInvalid': 'The profile owner record is damaged or belongs to another profile. Check the data directory.',
  'runtime.profileUnsupported': 'The profile owner record was created by an incompatible Orca version. Use a compatible version of the application.',
  'runtime.startupFailed': 'Could not open the Orca profile: {error}',
  'agentLaunch.settingsInvalid': 'Could not read Amp settings: {path}. Check the JSON/JSONC and file access.',
  'assistantTransport.missingCli': 'CLI {command} was not found. Install the agent and check PATH.',
  'assistantTransport.windowsLauncher': 'CLI {command} uses an unsupported Windows launcher. Use a native executable or a standard npm shim.',
  'assistantTransport.windowsEntry': 'Windows launcher entry was not found: {entry}',
  'assistantTransport.terminalOnly': 'Agent {agent} runs in a separate terminal; structured chat is not supported.',
  'assistantTransport.interruptedSend': 'The send was interrupted before agent acceptance. Your context is preserved.',
  'assistantTransport.invalidMessage': 'The message is empty or too long.',
  'assistantTransport.unavailable': 'The transport is unavailable.',
  'assistantTransport.busy': 'Wait for the reply or stop the current request.',
  'assistantTransport.closed': 'The chat is closed.',
  'assistantTransport.staleRequest': 'This request is no longer active.',
  'assistantTransport.writeUnavailable': 'The CLI is unavailable for writing.',
  'assistantTransport.timeout': 'The CLI did not confirm initialization or interruption. Check the agent version and authentication.',
  'assistantTransport.effortUnsupported': 'Agent {agent} does not support the selected effort through ACP.',
  'assistantTransport.modelUnsupported': 'Agent {agent} does not support model selection through ACP.',
  'assistantTransport.modelUnavailable': 'The CLI did not offer selected model {model}. Check its configuration.',
  'assistantTransport.startFailed': 'Could not start {command}: {error}',
  'assistantTransport.processExited': 'CLI {command} exited ({code}). {detail}',
  'assistantTransport.acpVersion': 'The CLI uses an incompatible ACP version; update the agent.',
  'assistantTransport.noSession': 'The CLI did not return a conversation identifier.',
  'assistantTransport.lineTooLarge': 'The CLI response exceeded the maximum line size.',
  'assistantTransport.invalidJson': 'The CLI returned invalid JSON. Check its structured mode support.',
  'assistantTransport.noTurn': 'Codex did not confirm the current turn.',
  'assistantTransport.codexFailed': 'Codex could not complete the turn.',
  'assistantTransport.codexError': 'Codex error.',
  'assistantTransport.unsupportedRequest': 'The CLI requested an unsupported capability: {method}. Update the agent or use a compatible version.',
  'assistantTransport.answerAll': 'Answer every question.',
  'assistantTransport.unknownQuestion': 'Unknown question or answer option.',
  'assistantTransport.unknownOption': 'Unknown answer option.',
  'assistantTransport.singleChoice': 'This question accepts one answer option.',
  'assistantTransport.freeformUnavailable': 'A freeform answer is unavailable.',
  'assistantTransport.answerRequired': 'Choose an option or enter an answer.',
  'assistantTransport.tool': 'Tool',
  'assistantTransport.command': 'Command',
  'assistantTransport.fileChange': 'File change',
  'assistantTransport.question': 'Question',
  'assistantTransport.plan': 'Plan',
  'assistantTransport.allow': 'Allow once',
  'assistantTransport.allowSession': 'Allow for session',
  'assistantTransport.deny': 'Deny',
  'assistantTransport.cancelTurn': 'Cancel turn',
  'assistantTransport.accept': 'Accept',
  'assistantTransport.reject': 'Reject',

  'common.none': 'none',

  'menu.about': 'About Orca',
  'menu.aboutCredits': 'A CLI agent orchestrator with a kanban board.\nTasks, separate Git branches and terminals in one app.',
  'about.version': 'Version {version}',
  'about.links': 'Project links',
  'about.project': 'Project on GitHub',
  'about.reportIssue': 'Report an issue',
  'about.author': 'Created by {author}',
  'menu.settings': 'Settings…',
  'menu.checkUpdates': 'Check for Updates…',
  'menu.quit': 'Quit orca-board',
  'menu.services': 'Services',
  'menu.hide': 'Hide orca-board',
  'menu.hideOthers': 'Hide Others',
  'menu.unhide': 'Show All',
  'menu.file': 'File',
  'menu.addProject': 'Add Repository…',
  'menu.close': 'Close Window',
  'menu.edit': 'Edit',
  'menu.undo': 'Undo',
  'menu.redo': 'Redo',
  'menu.cut': 'Cut',
  'menu.copy': 'Copy',
  'menu.paste': 'Paste',
  'menu.selectAll': 'Select All',
  'menu.view': 'View',
  'menu.resetZoom': 'Actual Size',
  'menu.zoomIn': 'Zoom In',
  'menu.zoomOut': 'Zoom Out',
  'menu.fullscreen': 'Toggle Full Screen',
  'menu.reload': 'Reload Window',
  'menu.devTools': 'Developer Tools',
  'menu.window': 'Window',
  'menu.showWindow': 'Show Main Window',
  'menu.minimize': 'Minimize',
  'menu.zoom': 'Zoom',
  'menu.front': 'Bring All to Front',
  'menu.help': 'Help',
  'menu.guide': 'orca-board User Guide',
  'menu.releases': 'What’s New',
  'menu.reportIssue': 'Report an Issue…',

  'tray.open': 'Open orca-board',
  'tray.active': 'Tasks in progress: {count}',
  'tray.restartUpdate': 'Restart and update to {version}',
  'tray.quit': 'Quit',

  'dialog.cancel': 'Cancel',
  'dialog.quit.message': {
    one: '{count} task is in progress, its agent will be stopped. Quit?',
    other: '{count} tasks are in progress, their agents will be stopped. Quit?'
  },
  'dialog.quit.quit': 'Quit',
  'dialog.update.idleReached': 'Agents have finished. Restart and update to {version}?',
  'dialog.update.restart': 'Restart and update',
  'dialog.update.later': 'Later',
  'dialog.update.busy': {
    one: '{count} task is in progress: update to {version} now (the agent will stop) or when agents finish?',
    other: '{count} tasks are in progress: update to {version} now (agents will stop) or when agents finish?'
  },
  'dialog.update.now': 'Update now',
  'dialog.update.whenIdle': 'When agents finish',
  'dialog.pickRepo': 'Choose a git repository',
  'dialog.exportType': 'Export task type',

  'notify.question': 'Question',
  'notify.workflowBlocked': 'Workflow stopped',
  'notify.escalation': 'Escalation',
  'notify.answerReady': 'Answer ready',
  'notify.awaitingDecision': 'Awaiting decision',
  'notify.readyForReview': 'Ready for review',
  'notify.runDone': 'Run finished',
  'notify.runSubtasksDone': 'Subtasks done, review coming up',
  'notify.testPreview': 'Question: this is how notifications will look',
  'notify.unsupported': 'system notifications are not supported',

  'column.backlog': 'Backlog',
  'column.ready': 'Ready',
  'column.in_progress': 'In progress',
  'column.needs_input': 'Needs input',
  'column.review': 'Review',
  'column.done': 'Done',

  'update.notReady': 'The update is not ready to install yet (state: {status}): wait for the download to finish',
  'update.checkFailed': 'Could not check for updates',
  'update.downloadFailed': 'Could not download the update',
  'update.installFailed': 'Could not install the update',

  'projects.none': 'no projects: add a repository',
  'projects.notGit': '{path} is not a git repository',
  'projects.groupNotFound': 'project group not found: {id}',
  'projects.groupNameEmpty': 'the project group name cannot be empty',

  'agent.unknown': 'unknown agent: {id}. Known: {known}',
  'agent.notInstalled': 'agent {id} is not installed (no {bin} binary in PATH)',
  'agent.disabled': 'agent {id} is disabled in the project settings (“About project”). Enabled: {enabled}',

  'role.missing': 'task type “{type}” has no role “{role}”. Type roles: {ids} (orca-board roles list).{hint}',
  'role.missing.systemHint': ' This is a system role — you can restore it: “Settings” → “Task types” → “{type}” → “Restore system roles”.',
  'role.missing.hint': ' Type roles are edited in “Settings” → “Task types”.',
  'role.noneLeft': 'at least one role is required',
  'role.emptyId': 'role #{n}: empty id',
  'role.duplicate': 'role “{id}” is listed twice',
  'role.emptyTitle': 'role “{id}”: empty name',
  'role.unknownAgent': 'role “{id}”: unknown agent {agent}',
  'role.descriptionNotString': 'role “{id}”: purpose must be a string',
  'role.modelNotString': 'role “{id}”: model must be a string',
  'role.effortNotString': 'role “{id}”: effort must be a string',
  'role.promptNotString': 'role “{id}”: system prompt must be a string',
  'role.extraArgsNotString': 'role “{id}”: launch flags must be a string',
  'role.extraArgsInvalid': 'role “{id}”: launch flags: {reason}',

  'assistant.notObject': 'assistant settings: an object is expected',
  'assistant.unknownAgent': 'assistant: unknown agent {agent}',
  'assistant.notString': 'assistant: field {field} must be a string',
  'assistant.extraArgsInvalid': 'assistant: launch flags: {reason}',

  'extraArgs.quote': 'unclosed quote {detail}',
  'extraArgs.separator': 'the “--” token is not allowed: everything after it, including the app’s own flags, would be read as the task text',
  'extraArgs.notFlag': 'the first item must be a flag (starting with “-”), not “{detail}”: only flags can be added, not a command',
  'extraArgs.control': 'control character {detail}',
  'extraArgs.length': 'the line is too long: {detail} characters, the maximum is {max}',
  'extraArgs.count': 'too many arguments: {detail}, the maximum is {max}',

  'worker.cannotStart': 'the worker will not start: {reason}',
  'coordinator.cannotStart': 'the coordinator will not start: {reason}',
  'coordinator.noObjective': 'no goal given',
  'coordinator.inboxNotTarget': '“Inbox” is not a coordinator goal: create a global task',
  'coordinator.alreadyRunning': 'the coordinator of this global task is already running (terminal {pty})',
  'coordinator.finishing': 'the coordinator of this global task is still finishing — try again in a few seconds',

  'attachments.noWorktree': 'the task has no worktree on disk — nowhere to save the attachments for the feedback (the task is already accepted or its worktree was removed)',
  'attachments.saveFailed': 'could not save the attachments: {error}',
  'attachments.invalid': 'the attachments were not accepted: {error}',
  'attachments.needText': 'the attachments need feedback text: describe what to fix',
  'attachments.notForAction': 'files can only be attached to “Clarify” and “Return”',

  'workflow.runFinished': 'the global task workflow has already finished — no coordinator is needed',
  'workflow.coordinatorNotRunning': 'your notes are saved, but the coordinator did not start — start it from the global task card (“Start coordinator”)',
  'global.notFound': 'global task not found: {id}',
  'global.coordinatorAlive': 'the coordinator of this global task is still running — close its terminal first',
  'global.typeRequired': 'choose a task type',
  'global.subtaskTitleEmpty': 'the subtask title cannot be empty',
  'global.imageNotFound': 'the global task has no attachment {imageId}',
  'global.imageFileMissing': 'the file of attachment {imageId} was not found on disk — remove the attachment and attach the file again',
  'global.notAnImage': 'attachment {imageId} is not an image: it has no preview, but it can be shown in its folder',
  'global.attachmentNotOpenable': 'attachment {imageId} cannot be opened from the app — it can be shown in its folder',
  'global.imagesEmpty': 'no attachments to add',
  'global.imagesSaveFailed': 'could not save the task attachments: {reason}',
  'global.approvalAmbiguous': {
    one: '{count} review request of the global task is waiting ({titles}) — resolve it in the Inbox',
    other: '{count} review requests of the global task are waiting ({titles}) — the card cannot tell which path to decide: resolve each one in the Inbox'
  },

  'column.noneLeft': 'at least one column is required',
  'column.emptyId': 'column #{n}: empty id',
  'column.duplicate': 'column “{id}” is listed twice',
  'column.emptyTitle': 'column “{id}”: empty name',
  'column.unknownKind': 'column “{id}”: unknown kind {kind}',
  'column.systemMissing': 'system column “{kind}” is missing — it cannot be deleted',
  'column.systemDuplicate': 'there must be one system column “{kind}”, found {n}',

  'type.label': 'type “{title}”',
  'type.notFound': 'task type not found: {id}',
  'type.snapshotFailed': 'could not preserve previous run settings from board {file}: {reason}',
  'type.snapshotBoardShape': 'invalid board structure',
  'type.snapshotRunShape': 'invalid run structure',
  'type.notFoundHint': 'task type not found: {id} (available: orca-board types list)',
  'type.unavailable': 'type “{title}” is not available in project “{project}” (available: orca-board types list)',
  'type.notObject': 'task type: an object is expected',
  'type.emptyId': 'task type: empty id',
  'type.emptyTitle': 'task type: empty name',
  'type.renameEmpty': 'specify --title and/or --description',
  'type.descriptionNotString': 'type “{title}”: description must be a string',
  'type.lastOne': 'type “{title}” is the last one in the library and cannot be deleted: create another type first',
  'type.copyTitle': '{title} (copy)',
  'type.noRole': 'type “{title}” has no role “{role}”',
  'type.settingsNotObject': '{label}: an object is expected',
  'type.unknownPermission': '{label}: unknown permission mode: {mode}',
  'type.exportFailed': 'could not save the task type file {path}: {reason}',

  'projectTypes.notObject': 'project types: an object is expected',
  'projectTypes.badIds': 'project types: typeIds must be an array of type ids',
  'projectTypes.empty': 'project types: at least one available type is required',
  'projectTypes.defaultNotAvailable': 'the default type “{title}” must be among the types available to the project',

  'runApproval.acceptHint': '“Accept” — continue along the workflow (usually the end or a merge), “Return” — with notes: the coordinator gets them and creates follow-up subtasks.',
  'runApproval.acceptHintLane': 'This node is on the “{lane}” path. “Accept” — the path moves on and reaches the join: the workflow continues once all paths arrive. “Return” — with notes: the coordinator gets them and reworks only this path, the other paths are not affected.',
  'runApproval.laneTitle': 'Path “{lane}”: {title}',

  'workflow.future': 'the workflow is saved in format version {version}, the app only knows {known} — update the app',
  'workflow.notSaved': 'workflow not saved: {errors}',
  'workflow.contextInvalid': 'The workflow context has an invalid shape. Return to the editor and attach the workflow again.',
  'workflow.conflict': 'type “{title}” changed since it was read: reload the graph and retry with the new revision',
  'workflow.selectors': 'use only one of --type and --base-type',

  'nodeTemplate.notObject': 'node template: an object is expected',
  'nodeTemplate.emptyId': 'node template: empty id',
  'nodeTemplate.emptyTitle': 'node template: empty title',
  'nodeTemplate.notFound': 'node template not found: {id}',
  'nodeTemplate.notSaved': 'node template not saved: {errors}',

  'rules.onlyKnown': 'only {a} and {b} in the project root can be edited, not “{name}”',
  'rules.brokenLink': '{name}: the link points to a missing file',
  'rules.linkOutside': '{name}: the link points outside the project',
  'rules.notFile': '{name}: not a file',
  'rules.fileTooBig': '{name}: the file is larger than {mb} MB',
  'rules.notString': '{name}: the text must be a string',
  'rules.textTooBig': '{name}: the text is larger than {mb} MB',
  'rules.writeFailed': '{name}: could not write — {error}',
  'rules.agentNotString': 'agent rules must be a string',
  'rules.roleNotString': 'role rules must be a string',

  'docs.project': 'Project',
  'docs.noTaskSource': 'the task is not in progress or has no worktree: {id}',
  'docs.noPath': 'no document path given',
  'docs.notRelative': 'the path must be relative: {path}',
  'docs.notMarkdown': 'not a markdown file: {path}',
  'docs.outside': 'the path is outside the project: {path}',
  'docs.notFound': 'file not found: {path}',
  'docs.notFile': 'not a file: {path}',
  'docs.tooBig': 'the file is larger than {mb} MB: {path}',
  'docs.notOpenable': 'this file type cannot be opened from the app: {path}',
  'docs.noPreview': 'no preview for this file: {path}',
  'files.badPath': 'invalid path: {path}',
  'files.outside': 'the path is outside the project: {path}',
  'files.hidden': 'the git service folder is not shown: {path}',
  'files.notFound': 'not found: {path}',
  'files.notDir': 'not a folder: {path}',
  'files.notFile': 'not a file: {path}',
  'files.rootMissing': 'the project folder is missing on disk: {path}',
  'files.readFailed': 'could not read {path}: {error}',

  'showcase.taskNotFound': 'showcase: task not found: {id}',
  'showcase.dispatchNotFound': 'showcase: worker launch {id} not found for this task',
  'showcase.noWorktree': 'showcase: task {id} has no worktree on disk — after a merge the files remain in the branch it was merged into',
  'showcase.noWorktreeBranch': 'showcase: task {id} has no worktree on disk — the files remain in branch {branch}',
  'showcase.noPath': 'showcase: no file path given',
  'showcase.notRelative': 'showcase: the path must be relative to the task repository root: {path}',
  'showcase.badType': 'showcase: this file type cannot be opened: {path}',
  'showcase.outside': 'showcase: the path is outside the task worktree: {path}',
  'showcase.notFound': 'showcase: file not found: {path} (the agent did not commit it or deleted it)',
  'showcase.notFile': 'showcase: not a file: {path}',
  'showcase.hidden': 'showcase: hidden files and folders are not shown: {path}',
  'showcase.noPreview': 'showcase: {path} has no preview — open it with the “Open” button',
  'showcase.networkNoSnapshot': 'showcase: internet is not available for this showcase — it has no snapshot, so the page would see the whole repository',
  'showcase.tooBig': 'showcase: the file is larger than {mb} MB: {path}',

  'review.noBranch': 'the task has no branch',
  'review.untracked': 'new files:',
  'review.notReviewable': 'task {id} is at stage “{node}” — there is nothing to accept or send back: the worker has not handed in the work yet or the stage awaits another decision',
  'review.stageBlocked': 'stage “{node}” of task {id} stopped again: {reason}',
  'git.runBranchFailed': 'could not create branch “{branch}” for the global task from “{base}”: {error}',
  'git.runBranchMissing': 'branch “{branch}” of the global task no longer exists in the repository — restore it or detach the branch from the task',
  'git.noCommits': 'The repository has no commits yet (branch “{branch}” is empty), and Orca branches work off a commit. Create an initial commit: with the “Create initial commit” button in the app or manually with `git add -A && git commit -m "init"`',
  'git.mergeTargetMissing': 'branch “{branch}” the task merges into does not exist — nothing was merged, the task branch and its commits are untouched: restore the branch and try again',
  'git.notRepo': '{path} is not a git repository',
  'git.dirtyTree': 'the project has uncommitted changes — the branch is not switched: commit or stash them first',
  'git.notFastForward': 'branch “{branch}” has diverged from {upstream}: fast-forward is not possible, combine the changes manually (merge or rebase)',
  'git.noUpstream': 'branch “{branch}” has no upstream — nothing to update it from',
  'git.branchBusy': 'branch “{branch}” is already checked out in another worktree: {path}',
  'git.workersActive': 'Orca agents are working in the project ({count}) — the root branch cannot be switched, wait for them to finish',
  'git.branchNotFound': 'branch “{branch}” exists neither locally nor on the remote',
  'git.opFailed': 'git {command}: {error}',
  'git.timeout': 'no response in {seconds} s',
  'request.alreadyCancelled': 'already decided: request {id} was cancelled',
  'request.alreadyResolved': 'already decided: request {id} was resolved',

  'stats.badRange': 'statistics: unknown period “{range}”, expected {expected}',
  'stats.noTask': 'statistics: task {id} is not in the project',
  'stats.noGlobal': 'statistics: global task {id} is not in the project',

  'assistantChat.unknownPty': "This assistant conversation is no longer active.",
  'assistantChat.emptyText': 'chat message is empty',
  'assistantChat.historyOnly': 'Saved conversations are read-only. Start a new conversation.',
  'assistantChat.historyLoad': 'Could not read conversation history. dialogs.json was left unchanged. Check file access and format; history from a newer version requires a compatible version of Orca.',
  'assistantChat.historyStorage': 'Could not save history. The conversation was stopped; the latest changes remain in memory until the app closes. Check access to dialogs.json and free disk space, then start a new conversation.',

  'onboarding.invalidInput': 'first-run wizard: an object with a boolean skipped field is expected'
} satisfies { [K in keyof typeof ru]: string | { one: string; other: string } }
