// Тексты main на русском — эталон ключей (en обязан иметь те же). Русские сообщения ошибок совпадают с тем, что
// получают сокет и CLI: `OrcaError.message` строится отсюда. Порядок — по областям: трей, диалоги, уведомления,
// ошибки по модулям.
export default {
  'common.none': 'нет',

  'tray.open': 'Открыть orca-board',
  'tray.active': 'Задач в работе: {count}',
  'tray.restartUpdate': 'Перезапустить и обновить до {version}',
  'tray.quit': 'Выйти',

  'dialog.cancel': 'Отмена',
  'dialog.quit.message': {
    one: '{count} задача в работе, агенты будут остановлены. Выйти?',
    few: '{count} задачи в работе, агенты будут остановлены. Выйти?',
    many: '{count} задач в работе, агенты будут остановлены. Выйти?'
  },
  'dialog.quit.quit': 'Выйти',
  'dialog.update.idleReached': 'Агенты закончили работу. Перезапустить и обновить до {version}?',
  'dialog.update.restart': 'Перезапустить и обновить',
  'dialog.update.later': 'Позже',
  'dialog.update.busy': {
    one: '{count} задача в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?',
    few: '{count} задачи в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?',
    many: '{count} задач в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?'
  },
  'dialog.update.now': 'Обновить сейчас',
  'dialog.update.whenIdle': 'Когда агенты закончат',
  'dialog.pickRepo': 'Выберите git-репозиторий',

  'notify.question': 'Вопрос',
  'notify.workflowBlocked': 'Воркфлоу остановлен',
  'notify.escalation': 'Эскалация',
  'notify.answerReady': 'Ответ готов',
  'notify.awaitingDecision': 'Ждёт решения',
  'notify.readyForReview': 'Готово к ревью',
  'notify.runDone': 'Прогон завершён',
  'notify.runSubtasksDone': 'Подзадачи сделаны, скоро проверка',
  'notify.testPreview': 'Вопрос: так уведомления и будут выглядеть',
  'notify.unsupported': 'системные уведомления не поддерживаются',

  // Встроенные колонки (`DEFAULT_COLUMNS`): подзаголовок уведомления, пока колонку не переименовали.
  'column.backlog': 'Бэклог',
  'column.ready': 'Готовы',
  'column.in_progress': 'В работе',
  'column.needs_input': 'Нужен ответ',
  'column.review': 'Ревью',
  'column.done': 'Сделано',

  'update.notReady': 'Обновление ещё не готово к установке (состояние: {status}): дождитесь окончания загрузки',
  'update.checkFailed': 'Не удалось проверить обновления',
  'update.downloadFailed': 'Не удалось скачать обновление',
  'update.installFailed': 'Не удалось установить обновление',

  'projects.none': 'нет проектов: добавьте репозиторий',
  'projects.notGit': '{path} — не git-репозиторий',
  'projects.groupNotFound': 'группа проектов не найдена: {id}',
  'projects.groupNameEmpty': 'название группы проектов не может быть пустым',

  'agent.unknown': 'неизвестный агент: {id}. Известные: {known}',
  'agent.notInstalled': 'агент {id} не установлен (нет бинарника {bin} в PATH)',
  'agent.disabled': 'агент {id} выключен в настройках проекта («О проекте»). Включены: {enabled}',

  'role.missing': 'роли «{role}» нет в типе задачи «{type}». Роли типа: {ids} (orca-board roles list).{hint}',
  'role.missing.systemHint': ' Это системная роль — её можно вернуть: «Настройки» → «Типы задач» → «{type}» → «Вернуть системные роли».',
  'role.missing.hint': ' Роли типа меняются в «Настройки» → «Типы задач».',
  'role.noneLeft': 'нужна хотя бы одна роль',
  'role.emptyId': 'роль №{n}: пустой id',
  'role.duplicate': 'роль «{id}» указана дважды',
  'role.emptyTitle': 'роль «{id}»: пустое название',
  'role.unknownAgent': 'роль «{id}»: неизвестный агент {agent}',
  'role.descriptionNotString': 'роль «{id}»: назначение должно быть строкой',
  'role.modelNotString': 'роль «{id}»: модель должна быть строкой',
  'role.effortNotString': 'роль «{id}»: effort должен быть строкой',
  'role.promptNotString': 'роль «{id}»: системный промпт должен быть строкой',

  'worker.cannotStart': 'воркер не запустится: {reason}',
  'coordinator.cannotStart': 'координатор не запустится: {reason}',
  'coordinator.noObjective': 'цель не задана',
  'coordinator.inboxNotTarget': '«Входящие» — не цель для координатора: создай глобальную задачу',
  'coordinator.alreadyRunning': 'координатор этой глобальной задачи уже работает (терминал {pty})',
  'coordinator.finishing': 'координатор этой глобальной задачи ещё завершается — повторите через несколько секунд',

  'workflow.runFinished': 'воркфлоу глобальной задачи уже дошёл до конца — координатор не нужен',
  'workflow.coordinatorNotRunning': 'замечания сохранены, но координатор не запустился — запусти его: карточка глобальной задачи → «Запустить координатора»',
  'global.notFound': 'глобальная задача не найдена: {id}',
  'global.coordinatorAlive': 'координатор этой глобальной задачи ещё работает — сначала закрой его терминал',
  'global.typeRequired': 'укажи тип задачи',
  'global.subtaskTitleEmpty': 'название подзадачи не может быть пустым',

  'column.noneLeft': 'нужна хотя бы одна колонка',
  'column.emptyId': 'колонка №{n}: пустой id',
  'column.duplicate': 'колонка «{id}» указана дважды',
  'column.emptyTitle': 'колонка «{id}»: пустое название',
  'column.unknownKind': 'колонка «{id}»: неизвестный вид {kind}',
  'column.systemMissing': 'нет системной колонки «{kind}» — её нельзя удалить',
  'column.systemDuplicate': 'системная колонка «{kind}» должна быть одна, а их {n}',

  'type.label': 'тип «{title}»',
  'type.notFound': 'тип задачи не найден: {id}',
  'type.notFoundHint': 'тип задачи не найден: {id} (доступные: orca-board types list)',
  'type.unavailable': 'тип «{title}» недоступен в проекте «{project}» (доступные: orca-board types list)',
  'type.notObject': 'тип задачи: ожидается объект',
  'type.emptyId': 'тип задачи: пустой id',
  'type.emptyTitle': 'тип задачи: пустое название',
  'type.descriptionNotString': 'тип «{title}»: описание должно быть строкой',
  'type.lastOne': 'тип «{title}» последний в библиотеке — его нельзя удалить: сначала создайте другой тип',
  'type.copyTitle': '{title} (копия)',
  'type.noRole': 'в типе «{title}» нет роли «{role}»',
  'type.settingsNotObject': '{label}: ожидается объект',
  'type.unknownPermission': '{label}: неизвестный режим разрешений: {mode}',

  'projectTypes.notObject': 'типы проекта: ожидается объект',
  'projectTypes.badIds': 'типы проекта: typeIds должен быть массивом id типов',
  'projectTypes.empty': 'типы проекта: нужен хотя бы один доступный тип',
  'projectTypes.defaultNotAvailable': 'тип по умолчанию «{title}» должен быть среди доступных проекту',

  'workflow.future': 'воркфлоу сохранён в формате версии {version}, приложение знает только {known} — обновите приложение',
  'workflow.notSaved': 'воркфлоу не сохранён: {errors}',

  'rules.onlyKnown': 'можно править только {a} и {b} в корне проекта, а не «{name}»',
  'rules.brokenLink': '{name}: ссылка ведёт на несуществующий файл',
  'rules.linkOutside': '{name}: ссылка ведёт за пределы проекта',
  'rules.notFile': '{name}: это не файл',
  'rules.fileTooBig': '{name}: файл больше {mb} МБ',
  'rules.notString': '{name}: текст должен быть строкой',
  'rules.textTooBig': '{name}: текст больше {mb} МБ',
  'rules.writeFailed': '{name}: не удалось записать — {error}',
  'rules.agentNotString': 'правила агентов должны быть строкой',
  'rules.roleNotString': 'правила роли должны быть строкой',

  'docs.project': 'Проект',
  'docs.noTaskSource': 'задача не в работе или без worktree: {id}',
  'docs.noPath': 'путь к документу не задан',
  'docs.notRelative': 'путь должен быть относительным: {path}',
  'docs.notMarkdown': 'не markdown-файл: {path}',
  'docs.outside': 'путь вне проекта: {path}',
  'docs.notFound': 'файл не найден: {path}',
  'docs.notFile': 'не файл: {path}',
  'docs.tooBig': 'файл больше {mb} МБ: {path}',

  'showcase.taskNotFound': 'показ: задача не найдена: {id}',
  'showcase.noWorktree': 'показ: у задачи {id} нет worktree',
  'showcase.noWorktreeBranch': 'показ: у задачи {id} нет worktree — файлы остались в ветке {branch}',
  'showcase.noPath': 'показ: путь к файлу не задан',
  'showcase.notRelative': 'показ: путь должен быть от корня репозитория задачи: {path}',
  'showcase.badType': 'показ: такой тип файла не открывается: {path}',
  'showcase.outside': 'показ: путь вне worktree задачи: {path}',
  'showcase.notFound': 'показ: файл не найден: {path} (агент не закоммитил его или удалил)',
  'showcase.notFile': 'показ: не файл: {path}',
  'showcase.noPreview': 'показ: {path} не превьюится — откройте его кнопкой «Открыть»',
  'showcase.tooBig': 'показ: файл больше {mb} МБ: {path}',

  'review.noBranch': 'у задачи нет ветки',
  'review.untracked': 'новые файлы:',
  'git.protectedBranch': 'мерж в «{branch}» запрещён: это общая ветка (настройка «О проекте → Git → Защищённые ветки»). Запустите задачу из глобальной задачи с веткой фичи или откройте в Orca worktree рабочей ветки',
  'git.runBranchFailed': 'не удалось завести ветку «{branch}» глобальной задачи от «{base}»: {error}',
  'git.runBranchMissing': 'ветки «{branch}» глобальной задачи больше нет в репозитории — восстановите её или снимите ветку с задачи',
  'git.badSettings': 'настройки Git проекта: {problems}',
  'request.alreadyCancelled': 'уже решено: запрос {id} отменён',
  'request.alreadyResolved': 'уже решено: запрос {id} решён',

  'stats.badRange': 'статистика: неизвестный период «{range}», ожидается {expected}',
  'stats.noTask': 'статистика: задачи {id} нет в проекте',
  'stats.noGlobal': 'статистика: глобальной задачи {id} нет в проекте',

  'onboarding.invalidInput': 'мастер первого запуска: ожидается объект с полем skipped (boolean)'
} satisfies Record<string, string | { one: string; few: string; many: string }>
