// Тексты main на русском — эталон ключей (en обязан иметь те же). Русские сообщения ошибок совпадают с тем, что
// получают сокет и CLI: `OrcaError.message` строится отсюда. Порядок — по областям: трей, диалоги, уведомления,
// ошибки по модулям.
export default {
  'assistantTransport.missingCli': 'Не найден CLI {command}. Установите агент и проверьте PATH.',
  'assistantTransport.windowsLauncher': 'CLI {command} использует неподдерживаемый Windows launcher. Укажите native executable или стандартный npm shim.',
  'assistantTransport.windowsEntry': 'Не найден файл Windows launcher: {entry}',
  'assistantTransport.terminalOnly': 'Агент {agent} работает через отдельный терминал; структурированный чат не поддерживается.',
  'assistantTransport.invalidMessage': 'Сообщение пустое или слишком длинное.',
  'assistantTransport.unavailable': 'Транспорт недоступен.',
  'assistantTransport.busy': 'Дождитесь ответа или остановите текущий запрос.',
  'assistantTransport.closed': 'Чат закрыт.',
  'assistantTransport.staleRequest': 'Запрос больше не активен.',
  'assistantTransport.writeUnavailable': 'CLI недоступен для записи.',
  'assistantTransport.timeout': 'CLI не подтвердил инициализацию или остановку. Проверьте версию и авторизацию агента.',
  'assistantTransport.effortUnsupported': 'Агент {agent} не поддерживает выбранный effort через ACP.',
  'assistantTransport.modelUnsupported': 'Агент {agent} не поддерживает выбор модели через ACP.',
  'assistantTransport.modelUnavailable': 'CLI не предложил выбранную модель {model}. Проверьте её настройку.',
  'assistantTransport.startFailed': 'Ошибка запуска {command}: {error}',
  'assistantTransport.processExited': 'CLI {command} завершился ({code}). {detail}',
  'assistantTransport.acpVersion': 'CLI использует несовместимую версию ACP; обновите агент.',
  'assistantTransport.noSession': 'CLI не вернул идентификатор беседы.',
  'assistantTransport.lineTooLarge': 'Ответ CLI превысил допустимый размер строки.',
  'assistantTransport.invalidJson': 'CLI вернул некорректный JSON. Проверьте поддержку структурированного режима.',
  'assistantTransport.noTurn': 'Codex не подтвердил текущий ход.',
  'assistantTransport.codexFailed': 'Codex не завершил запрос.',
  'assistantTransport.codexError': 'Ошибка Codex.',
  'assistantTransport.unsupportedRequest': 'CLI запросил неподдерживаемую возможность: {method}. Обновите агент или выберите совместимую версию.',
  'assistantTransport.answerAll': 'Ответьте на каждый вопрос.',
  'assistantTransport.unknownQuestion': 'Неизвестный вопрос или вариант ответа.',
  'assistantTransport.unknownOption': 'Неизвестный вариант ответа.',
  'assistantTransport.singleChoice': 'Для вопроса нужен один вариант ответа.',
  'assistantTransport.freeformUnavailable': 'Произвольный ответ недоступен.',
  'assistantTransport.answerRequired': 'Выберите вариант или введите ответ.',
  'assistantTransport.tool': 'Инструмент',
  'assistantTransport.command': 'Команда',
  'assistantTransport.fileChange': 'Изменение файлов',
  'assistantTransport.question': 'Вопрос',
  'assistantTransport.plan': 'План',
  'assistantTransport.allow': 'Разрешить один раз',
  'assistantTransport.allowSession': 'Разрешить на время беседы',
  'assistantTransport.deny': 'Отклонить',
  'assistantTransport.cancelTurn': 'Остановить запрос',
  'assistantTransport.accept': 'Принять',
  'assistantTransport.reject': 'Отклонить',

  'common.none': 'нет',

  'menu.about': 'О приложении Orca',
  'menu.aboutCredits': 'Оркестратор CLI-агентов с канбан-доской.\nЗадачи, отдельные Git-ветки и терминалы — в одном приложении.',
  'about.version': 'Версия {version}',
  'about.links': 'Ссылки проекта',
  'about.project': 'Проект на GitHub',
  'about.reportIssue': 'Сообщить об ошибке',
  'about.author': 'Создано {author}',
  'menu.settings': 'Настройки…',
  'menu.checkUpdates': 'Проверить обновления…',
  'menu.quit': 'Выйти из orca-board',
  'menu.services': 'Службы',
  'menu.hide': 'Скрыть orca-board',
  'menu.hideOthers': 'Скрыть остальные',
  'menu.unhide': 'Показать все',
  'menu.file': 'Файл',
  'menu.addProject': 'Добавить репозиторий…',
  'menu.close': 'Закрыть окно',
  'menu.edit': 'Правка',
  'menu.undo': 'Отменить',
  'menu.redo': 'Повторить',
  'menu.cut': 'Вырезать',
  'menu.copy': 'Копировать',
  'menu.paste': 'Вставить',
  'menu.selectAll': 'Выбрать всё',
  'menu.view': 'Вид',
  'menu.resetZoom': 'Настоящий размер',
  'menu.zoomIn': 'Увеличить',
  'menu.zoomOut': 'Уменьшить',
  'menu.fullscreen': 'Полноэкранный режим',
  'menu.reload': 'Перезагрузить окно',
  'menu.devTools': 'Инструменты разработчика',
  'menu.window': 'Окно',
  'menu.showWindow': 'Показать главное окно',
  'menu.minimize': 'Свернуть',
  'menu.zoom': 'Изменить размер',
  'menu.front': 'Все окна на передний план',
  'menu.help': 'Справка',
  'menu.guide': 'Руководство orca-board',
  'menu.releases': 'Что нового',
  'menu.reportIssue': 'Сообщить об ошибке…',

  'tray.open': 'Открыть orca-board',
  'tray.active': 'Задач в работе: {count}',
  'tray.restartUpdate': 'Перезапустить и обновить до {version}',
  'tray.quit': 'Выйти',

  'dialog.cancel': 'Отмена',
  'dialog.quit.message': {
    one: '{count} задача в работе, агенты будут остановлены. Выйти?',
    few: '{count} задачи в работе, агенты будут остановлены. Выйти?',
    many: '{count} задач в работе, агенты будут остановлены. Выйти?'
  },
  'dialog.quit.quit': 'Выйти',
  'dialog.update.idleReached': 'Агенты закончили работу. Перезапустить и обновить до {version}?',
  'dialog.update.restart': 'Перезапустить и обновить',
  'dialog.update.later': 'Позже',
  'dialog.update.busy': {
    one: '{count} задача в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?',
    few: '{count} задачи в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?',
    many: '{count} задач в работе: обновить до {version} сейчас (агенты остановятся) или когда агенты закончат?'
  },
  'dialog.update.now': 'Обновить сейчас',
  'dialog.update.whenIdle': 'Когда агенты закончат',
  'dialog.pickRepo': 'Выберите git-репозиторий',
  'dialog.exportType': 'Экспорт типа задач',

  'notify.question': 'Вопрос',
  'notify.workflowBlocked': 'Воркфлоу остановлен',
  'notify.escalation': 'Эскалация',
  'notify.answerReady': 'Ответ готов',
  'notify.awaitingDecision': 'Ждёт решения',
  'notify.readyForReview': 'Готово к ревью',
  'notify.runDone': 'Прогон завершён',
  'notify.runSubtasksDone': 'Подзадачи сделаны, скоро проверка',
  'notify.testPreview': 'Вопрос: так уведомления и будут выглядеть',
  'notify.unsupported': 'системные уведомления не поддерживаются',

  // Встроенные колонки (`DEFAULT_COLUMNS`): подзаголовок уведомления, пока колонку не переименовали.
  'column.backlog': 'Бэклог',
  'column.ready': 'Готовы',
  'column.in_progress': 'В работе',
  'column.needs_input': 'Нужен ответ',
  'column.review': 'Ревью',
  'column.done': 'Сделано',

  'update.notReady': 'Обновление ещё не готово к установке (состояние: {status}): дождитесь окончания загрузки',
  'update.checkFailed': 'Не удалось проверить обновления',
  'update.downloadFailed': 'Не удалось скачать обновление',
  'update.installFailed': 'Не удалось установить обновление',

  'projects.none': 'нет проектов: добавьте репозиторий',
  'projects.notGit': '{path} — не git-репозиторий',
  'projects.groupNotFound': 'группа проектов не найдена: {id}',
  'projects.groupNameEmpty': 'название группы проектов не может быть пустым',

  'agent.unknown': 'неизвестный агент: {id}. Известные: {known}',
  'agent.notInstalled': 'агент {id} не установлен (нет бинарника {bin} в PATH)',
  'agent.disabled': 'агент {id} выключен в настройках проекта («О проекте»). Включены: {enabled}',

  'role.missing': 'роли «{role}» нет в типе задачи «{type}». Роли типа: {ids} (orca-board roles list).{hint}',
  'role.missing.systemHint': ' Это системная роль — её можно вернуть: «Настройки» → «Типы задач» → «{type}» → «Вернуть системные роли».',
  'role.missing.hint': ' Роли типа меняются в «Настройки» → «Типы задач».',
  'role.noneLeft': 'нужна хотя бы одна роль',
  'role.emptyId': 'роль №{n}: пустой id',
  'role.duplicate': 'роль «{id}» указана дважды',
  'role.emptyTitle': 'роль «{id}»: пустое название',
  'role.unknownAgent': 'роль «{id}»: неизвестный агент {agent}',
  'role.descriptionNotString': 'роль «{id}»: назначение должно быть строкой',
  'role.modelNotString': 'роль «{id}»: модель должна быть строкой',
  'role.effortNotString': 'роль «{id}»: effort должен быть строкой',
  'role.promptNotString': 'роль «{id}»: системный промпт должен быть строкой',
  'role.extraArgsNotString': 'роль «{id}»: флаги запуска должны быть строкой',
  'role.extraArgsInvalid': 'роль «{id}»: флаги запуска: {reason}',

  'assistant.notObject': 'настройки ассистента: ожидается объект',
  'assistant.unknownAgent': 'ассистент: неизвестный агент {agent}',
  'assistant.notString': 'ассистент: поле {field} должно быть строкой',
  'assistant.extraArgsInvalid': 'ассистент: флаги запуска: {reason}',

  // Почему строку флагов запуска нельзя принять (`ExtraArgsError` в core) — параметр {reason} ошибок выше.
  'extraArgs.quote': 'незакрытая кавычка {detail}',
  'extraArgs.separator': 'токен «--» недопустим: всё после него, включая флаги приложения, агент принял бы за текст задания',
  'extraArgs.notFlag': 'первым должен идти флаг (начинается с «-»), а не «{detail}»: дописываются только флаги, не команда',
  'extraArgs.control': 'управляющий символ {detail}',
  'extraArgs.length': 'строка слишком длинная: {detail} символов при максимуме {max}',
  'extraArgs.count': 'слишком много аргументов: {detail} при максимуме {max}',

  'worker.cannotStart': 'воркер не запустится: {reason}',
  'coordinator.cannotStart': 'координатор не запустится: {reason}',
  'coordinator.noObjective': 'цель не задана',
  'coordinator.inboxNotTarget': '«Входящие» — не цель для координатора: создай глобальную задачу',
  'coordinator.alreadyRunning': 'координатор этой глобальной задачи уже работает (терминал {pty})',
  'coordinator.finishing': 'координатор этой глобальной задачи ещё завершается — повторите через несколько секунд',

  'attachments.noWorktree': 'у задачи нет worktree на диске — изображения к замечаниям сохранять некуда (задача уже принята или её worktree удалён)',
  'attachments.saveFailed': 'не удалось сохранить изображения: {error}',
  'attachments.invalid': 'изображения не приняты: {error}',
  'attachments.needText': 'к изображениям нужен текст замечаний: опиши, что исправить',
  'attachments.notForAction': 'изображения можно приложить только к «Уточнить» и «Вернуть»',

  'workflow.runFinished': 'воркфлоу глобальной задачи уже дошёл до конца — координатор не нужен',
  'workflow.coordinatorNotRunning': 'замечания сохранены, но координатор не запустился — запусти его: карточка глобальной задачи → «Запустить координатора»',
  'global.notFound': 'глобальная задача не найдена: {id}',
  'global.coordinatorAlive': 'координатор этой глобальной задачи ещё работает — сначала закрой его терминал',
  'global.typeRequired': 'укажи тип задачи',
  'global.subtaskTitleEmpty': 'название подзадачи не может быть пустым',
  'global.imageNotFound': 'у глобальной задачи нет изображения {imageId}',
  'global.imageFileMissing': 'файл изображения {imageId} не найден на диске — удалите картинку и приложите её заново',
  'global.imagesEmpty': 'нет изображений для добавления',
  'global.imagesSaveFailed': 'не удалось сохранить изображения задачи: {reason}',

  'column.noneLeft': 'нужна хотя бы одна колонка',
  'column.emptyId': 'колонка №{n}: пустой id',
  'column.duplicate': 'колонка «{id}» указана дважды',
  'column.emptyTitle': 'колонка «{id}»: пустое название',
  'column.unknownKind': 'колонка «{id}»: неизвестный вид {kind}',
  'column.systemMissing': 'нет системной колонки «{kind}» — её нельзя удалить',
  'column.systemDuplicate': 'системная колонка «{kind}» должна быть одна, а их {n}',

  'type.label': 'тип «{title}»',
  'type.notFound': 'тип задачи не найден: {id}',
  'type.notFoundHint': 'тип задачи не найден: {id} (доступные: orca-board types list)',
  'type.unavailable': 'тип «{title}» недоступен в проекте «{project}» (доступные: orca-board types list)',
  'type.notObject': 'тип задачи: ожидается объект',
  'type.emptyId': 'тип задачи: пустой id',
  'type.emptyTitle': 'тип задачи: пустое название',
  'type.renameEmpty': 'укажи --title и/или --description',
  'type.descriptionNotString': 'тип «{title}»: описание должно быть строкой',
  'type.lastOne': 'тип «{title}» последний в библиотеке — его нельзя удалить: сначала создайте другой тип',
  'type.copyTitle': '{title} (копия)',
  'type.noRole': 'в типе «{title}» нет роли «{role}»',
  'type.settingsNotObject': '{label}: ожидается объект',
  'type.unknownPermission': '{label}: неизвестный режим разрешений: {mode}',
  'type.exportFailed': 'не удалось сохранить файл типа {path}: {reason}',

  'projectTypes.notObject': 'типы проекта: ожидается объект',
  'projectTypes.badIds': 'типы проекта: typeIds должен быть массивом id типов',
  'projectTypes.empty': 'типы проекта: нужен хотя бы один доступный тип',
  'projectTypes.defaultNotAvailable': 'тип по умолчанию «{title}» должен быть среди доступных проекту',

  'workflow.future': 'воркфлоу сохранён в формате версии {version}, приложение знает только {known} — обновите приложение',
  'workflow.notSaved': 'воркфлоу не сохранён: {errors}',

  'nodeTemplate.notObject': 'шаблон нод: ожидается объект',
  'nodeTemplate.emptyId': 'шаблон нод: пустой id',
  'nodeTemplate.emptyTitle': 'шаблон нод: пустое название',
  'nodeTemplate.notFound': 'шаблон нод не найден: {id}',
  'nodeTemplate.notSaved': 'шаблон нод не сохранён: {errors}',

  'rules.onlyKnown': 'можно править только {a} и {b} в корне проекта, а не «{name}»',
  'rules.brokenLink': '{name}: ссылка ведёт на несуществующий файл',
  'rules.linkOutside': '{name}: ссылка ведёт за пределы проекта',
  'rules.notFile': '{name}: это не файл',
  'rules.fileTooBig': '{name}: файл больше {mb} МБ',
  'rules.notString': '{name}: текст должен быть строкой',
  'rules.textTooBig': '{name}: текст больше {mb} МБ',
  'rules.writeFailed': '{name}: не удалось записать — {error}',
  'rules.agentNotString': 'правила агентов должны быть строкой',
  'rules.roleNotString': 'правила роли должны быть строкой',

  'docs.project': 'Проект',
  'docs.noTaskSource': 'задача не в работе или без worktree: {id}',
  'docs.noPath': 'путь к документу не задан',
  'docs.notRelative': 'путь должен быть относительным: {path}',
  'docs.notMarkdown': 'не markdown-файл: {path}',
  'docs.outside': 'путь вне проекта: {path}',
  'docs.notFound': 'файл не найден: {path}',
  'docs.notFile': 'не файл: {path}',
  'docs.tooBig': 'файл больше {mb} МБ: {path}',
  'docs.notOpenable': 'такой файл нельзя открыть из приложения: {path}',
  'docs.noPreview': 'у файла нет превью: {path}',
  'files.badPath': 'недопустимый путь: {path}',
  'files.outside': 'путь вне проекта: {path}',
  'files.hidden': 'служебная папка git не показывается: {path}',
  'files.notFound': 'не найдено: {path}',
  'files.notDir': 'не папка: {path}',
  'files.notFile': 'не файл: {path}',
  'files.rootMissing': 'папки проекта нет на диске: {path}',
  'files.readFailed': 'не удалось прочитать {path}: {error}',

  'showcase.taskNotFound': 'показ: задача не найдена: {id}',
  'showcase.dispatchNotFound': 'показ: запуск {id} не найден у этой задачи',
  'showcase.noWorktree': 'показ: у задачи {id} нет worktree на диске — после мержа файлы остаются в ветке, куда её слили',
  'showcase.noWorktreeBranch': 'показ: у задачи {id} нет worktree на диске — файлы остались в ветке {branch}',
  'showcase.noPath': 'показ: путь к файлу не задан',
  'showcase.notRelative': 'показ: путь должен быть от корня репозитория задачи: {path}',
  'showcase.badType': 'показ: такой тип файла не открывается: {path}',
  'showcase.outside': 'показ: путь вне worktree задачи: {path}',
  'showcase.notFound': 'показ: файл не найден: {path} (агент не закоммитил его или удалил)',
  'showcase.notFile': 'показ: не файл: {path}',
  'showcase.hidden': 'показ: скрытые файлы и папки не показываются: {path}',
  'showcase.noPreview': 'показ: {path} не превьюится — откройте его кнопкой «Открыть»',
  'showcase.networkNoSnapshot': 'показ: интернет недоступен для этого показа — он сдан без снимка, страница видела бы весь репозиторий',
  'showcase.tooBig': 'показ: файл больше {mb} МБ: {path}',

  'review.noBranch': 'у задачи нет ветки',
  'review.untracked': 'новые файлы:',
  'review.notReviewable': 'задача {id} на этапе «{node}» — принимать или возвращать нечего: воркер ещё не сдал работу или этап ждёт другого решения',
  'review.stageBlocked': 'этап «{node}» задачи {id} снова остановлен: {reason}',
  'git.runBranchFailed': 'не удалось завести ветку «{branch}» глобальной задачи от «{base}»: {error}',
  'git.runBranchMissing': 'ветки «{branch}» глобальной задачи больше нет в репозитории — восстановите её или снимите ветку с задачи',
  'git.noCommits': 'В репозитории нет ни одного коммита (ветка «{branch}» пуста), а Orca ветвит работу от коммита. Создайте начальный коммит: кнопкой «Создать начальный коммит» в приложении или вручную `git add -A && git commit -m "init"`',
  'git.mergeTargetMissing': 'ветки «{branch}», в которую сливается задача, нет — слияние не выполнено, ветка задачи и её коммиты не тронуты: восстановите ветку и повторите',
  'git.notRepo': '{path} — не git-репозиторий',
  'git.dirtyTree': 'в проекте есть незакоммиченные изменения — переключение ветки не выполняется: закоммитьте или отложите их',
  'git.notFastForward': 'ветка «{branch}» разошлась с {upstream}: fast-forward невозможен, объедините изменения вручную (merge или rebase)',
  'git.noUpstream': 'у ветки «{branch}» нет upstream — обновлять её не из чего',
  'git.branchBusy': 'ветка «{branch}» уже открыта в другом worktree: {path}',
  'git.workersActive': 'в проекте работают агенты Orca ({count}) — переключать ветку корня нельзя, дождитесь их завершения',
  'git.branchNotFound': 'ветки «{branch}» нет ни локально, ни на remote',
  'git.opFailed': 'git {command}: {error}',
  'git.timeout': 'не ответил за {seconds} с',
  'request.alreadyCancelled': 'уже решено: запрос {id} отменён',
  'request.alreadyResolved': 'уже решено: запрос {id} решён',

  'stats.badRange': 'статистика: неизвестный период «{range}», ожидается {expected}',
  'stats.noTask': 'статистика: задачи {id} нет в проекте',
  'stats.noGlobal': 'статистика: глобальной задачи {id} нет в проекте',

  'assistantChat.unknownPty': "Этот диалог ассистента больше не активен.",
  'assistantChat.emptyText': 'пустое сообщение чата',

  'onboarding.invalidInput': 'мастер первого запуска: ожидается объект с полем skipped (boolean)'
} satisfies Record<string, string | { one: string; few: string; many: string }>
